name: open_route_service
description: An encapsulation made around openrouteservice APIs, for Dart and Flutter projects, to easily generate Routes and their data. 
version: 1.2.2
repository: https://github.com/dhi13man/open_route_service/
homepage: https://github.com/dhi13man/open_route_service/
issue_tracker: https://github.com/Dhi13man/open_route_service/issues

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies: 
  http: ^1.0.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.20.1
